### ISSUE TITLE
I would love to see this in PackageControl

### ISSUE THREAD

**Issue by dotHTM** [mawelborn/ZipContents#1]
After Atlassian shut down their `hg` service in August, the similar plugin "Zip Browser" and all the other plugins of that author went "Missing".

Your plugin seems to function similarly to that one, and I think it would be a great service to the Sublime Text community for you to submit yours.

<https://packagecontrol.io/docs>

It's easy, and I've done it myself for my color scheme <https://packagecontrol.io/packages/Teenage%20Color%20Scheme>!

**Comment by mawelborn** [comment]
Thanks for letting me know! I've submitted a pull request to add it to Package Control. I didn't originally because the plugin you mentioned was already there, but it being missing is a good reason to do so now.
