### ISSUE TITLE
When opening a zip file from the file finder (ctrl+p), the quick panel fails to open with error "AttributeError: 'NoneType' object has no attribute 'show_quick_panel'"

### ISSUE THREAD

**Issue by jkhoriaty** [mawelborn/ZipContents#2]
Opening a zip file from the side panel works fine, but not when found through the file finder.
Full traceback:

> Traceback (most recent call last):
>   File "C:\Software\Sublime Text 3\Lib\python33\sublime_plugin.py", line 859, in on_load
>     run_view_callbacks('on_load', view_id)
>   File "C:\Software\Sublime Text 3\Lib\python33\sublime_plugin.py", line 708, in run_view_callbacks
>     callback(v, *args)
>   File "C:\Software\Sublime Text 3\Lib\python33\sublime_plugin.py", line 152, in profiler
>     return event_handler(*args)
>   File "C:\Users\ ________\AppData\Roaming\Sublime Text\Installed Packages\ZipContents.sublime-package\ZipContents.py", line 28, in on_load
>     show_zip_contents(view)
>   File "C:\Users\ ________\AppData\Roaming\Sublime Text\Installed Packages\ZipContents.sublime-package\ZipContents.py", line 36, in show_zip_contents
>     zip_window.show_quick_panel(zip_contents, extract_file)
> AttributeError: 'NoneType' object has no attribute 'show_quick_panel'

**Comment by mawelborn** [comment]
I never quite finished getting ZipContents to play nice with Goto Anything. From an API perspective, transient previews loaded behind the Goto Anything quick panel are indistinguishable from intransient views loaded by other means. So if you happen to preview a zip file while filtering Goto Anything, ZipContents will steal the quick panel from you. Or if `view.window()` is `None` for whatever reason, it just does nothing as you experienced. Neither is a great user experience.

Ideally it would "just work" where contents are shown only after a zip file is selected with Goto Anything, not just previewed. I think I've found a way to track whether Goto Anything is open on both ST3 and 4 and can use that to make it show contents only after a selection has been made. If not, your PR to add a command to manually display contents is a good workaround.

**Comment by mawelborn** [comment]
Version 2.1.0 is live on Package Control that fixes this issue and generally improves behavior when opening files with Goto Anything.

Thanks for opening a PR and giving me the motivation to come back to this and make it better!
